export const GET_GARMENTS = 'GET_GARMENTS';
export const GARMENTS_LOADING ='GARMENTS_LOADING'
export const ADD_GARMENT = 'ADD_GARMENT';
export const GARMENTS_ADDING = 'GARMENTS_ADDING';
export const DELETE_GARMENT = 'DELETE_GARMENT';